# Generated by Django 3.2.3 on 2021-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='secondary_memory',
            field=models.CharField(choices=[('HDD', 'Hard Disk Drive'), ('SSD', 'Solid State Drive')], max_length=3, verbose_name='Secondary Memory Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_storage',
            field=models.IntegerField(choices=[(256, '256 GB'), (512, '512 GB'), (1024, '1 TB'), (2048, '2 TB')], verbose_name='Secondary Storage Capacity'),
        ),
    ]
